services:
  - type: web
    name: VVV-8
    env: node
    plan: free
    branch: main
    root: gigastudio-d61998ff
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
