services:
  - type: static
    name: VVV-8
    env: static
    plan: free
    branch: main
    root: .
    buildCommand: npm install && npm run build && npm run export
    publishPath: out
    autoDeploy: true
